apps/members/urls.py
from django.urls import path

from apps.members import views

urlpatterns = [
    path('list-members/', views.members, name="list-members"),
    path('member_details/<str:pk>', views.member_details, name='member_details'),
    path('export_pdf/', views.export_pdf, name='export_pdf'),
    path('export_excel/', views.export_excel, name='export_excel'),
]

crp/urls.py
# -*- encoding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),  
    path("", include("apps.authentication.urls")),  # Auth routes - login / register

    # ADD NEW Routes HERE
    path("", include("apps.vocacionados.urls")),
    path("", include('apps.members.urls')),
    path("", include("apps.home.urls")),
    path("", include("apps.voluntarios.urls")),
    path("", include("apps.pastorais.urls")),
    path("", include("apps.elos.urls")),
    path("", include("apps.historico.urls")),
]

apps/members/models.py
from django.core.exceptions import ValidationError
from django.db import models

from apps.pastorais.models import Pastorais
from crp import settings

class Profession(models.Model):
    class Meta:
        ordering = ['name']
        db_table = 'Profession'
        verbose_name = 'Profissão'
        verbose_name_plural = 'Profissões'

    name = models.CharField(max_length=255, null=False, blank=False, verbose_name='Profissão')
    updateAt = models.DateTimeField(null=False, blank=False, editable=False, auto_now=True)
    createAt = models.DateTimeField(null=False, blank=False, editable=False, auto_now_add=True)

    def __str__(self):
        return self.name

    def clean(self):
        # Check for duplicate elos with the same nome
        existing_profession = Profession.objects.filter(name=self.name).exclude(id=self.id)
        if existing_profession.exists():
            raise ValidationError('Esta Profissão já foi cadastrado(a).')

    def save(self, *args, **kwargs):
        self.full_clean()  # Run full validation before saving
        super().save(*args, **kwargs)


class Membros(models.Model):
    class Meta:
        verbose_name_plural = 'Membros'
        verbose_name = 'Membro'

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True,
                                verbose_name='Usuario')
    nome_completo = models.CharField(max_length=255, null=False, blank=False, verbose_name='Nome Completo')
    dt_nascimento = models.DateField(null=False, blank=False, verbose_name='Data de Nascimento')
    cpf = models.CharField(max_length=14, null=False, blank=False, verbose_name='CPF')
    sexo_choices = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    ]
    sexo = models.CharField(max_length=1, null=False, blank=False, choices=sexo_choices, verbose_name='Sexo')
    telefone = models.CharField(max_length=20, null=True, blank=True, verbose_name='Telefone')
    celular = models.CharField(max_length=20, null=False, blank=False, verbose_name='Celular')
    email = models.EmailField(null=False, blank=False, verbose_name='Email')
    observacao = models.TextField(max_length=500, null=True, blank=True, verbose_name='Observação')
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name='Endereço')
    neighborhood = models.CharField(max_length=50, null=True, blank=True, verbose_name='Bairro')
    city = models.CharField(max_length=50, null=True, blank=True, verbose_name='Cidade')
    state = models.CharField(max_length=50, null=True, blank=True, verbose_name='Estado')
    cep = models.CharField(max_length=10, null=True, blank=True, verbose_name='CEP')
    conjugue = models.CharField(max_length=200, null=True, blank=True, verbose_name='Conjugue')
    marital_status_choices = [
        ('Solteiro', 'Solteiro'),
        ('Casado', 'Casado'),
        ('Separado', 'Separado'),
        ('Divorciado', 'Divorciado'),
        ('Viuvo', 'Viúvo'),
    ]
    estado_civil = models.CharField(max_length=20, null=False, blank=False, choices=marital_status_choices,
                                    verbose_name='Estado Civil')
    profession = models.ForeignKey(Profession, on_delete=models.CASCADE, blank=True, null=True,
                                   verbose_name='Profissão')
    aposentado = models.BooleanField(default=False, null=True, blank=True, verbose_name='Aposentado')
    afastado = models.BooleanField(default=False, null=True, blank=True, verbose_name='Afastado')
    falecido = models.BooleanField(default=False, null=True, blank=True, verbose_name='Falecido')
    atestado_obito = models.FileField(upload_to='atestado_obito/%d-%m-%Y', blank=True, null=True, verbose_name='Atestado de Obito')
    education_choices = [
        ('aprendizado_online', 'Aprendizado Online'),
        ('bacharelado', 'Bacharelado'),
        ('doutorado', 'Doutorado'),
        ('educacao_continuada', 'Educação Continuada'),
        ('ensino fundamental', 'Ensino Fundamental'),
        ('ensino medio', 'Ensino Médio'),
        ('especializacao', 'Especialização'),
        ('graduacao', 'Graduação'),
        ('licenciatura', 'Licenciatura'),
        ('mestrado', 'Mestrado'),
        ('mba', 'MBA (Master of Business Administration)'),
        ('phd', 'Ph.D.'),
        ('pos-graduacao', 'Pós-graduação'),
        ('tecnico', 'Técnico'),
        ('tecnologo', 'Tecnologo'),
    ]

    education = models.CharField(max_length=22, null=True, blank=True, choices=education_choices,
                                 verbose_name='Formação')
    dt_promessa = models.DateField(null=True, blank=True, verbose_name='Data da Promessa')
    dt_matrimonio = models.DateField(null=True, blank=True, verbose_name='Data do Matrimonio')
    mentor = models.CharField(max_length=255, null=True, blank=True, verbose_name='Orientador(a)')
    imagem_perfil = models.ImageField(upload_to='profile_images/%d-%m-%Y', blank=True, null=True)
    pastorais = models.ManyToManyField(Pastorais, related_name='membros',
                                       verbose_name='Pastorais', blank=True)
    elo_choices = [
        ('1_elo', '1º elo'),
        ('2_elo', '2º elo'),
        ('3_elo', '3º elo'),
    ]

    elo = models.CharField(max_length=50, null=False, blank=False, choices=elo_choices)
    criadoEm = models.DateTimeField(null=False, blank=False, editable=False,
                                    auto_now_add=True,
                                    verbose_name='Criado Em')
    atualizadoEm = models.DateTimeField(null=False, blank=False, editable=False,
                                        auto_now=True,
                                        verbose_name='Atualizado Em')

    def __str__(self):
        return f'{self.nome_completo} '


class Formadores(models.Model):
    class Meta:
        verbose_name = 'Formador'
        verbose_name_plural = 'Formadores'

    nome = models.CharField(max_length=255, null=False, blank=False, verbose_name='Nome')
    membro = models.ManyToManyField(Membros, related_name='formadores',
                                    verbose_name='Membro Associado', blank=True)

    def __str__(self):
        return f'{self.nome} ({self.membro.count()} membros associados)'

apps/members/forms.py
from django import forms

from apps.members.models import Membros


class MembrosFormAdmin(forms.ModelForm):
    class Meta:
        model = Membros
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cpf'].widget.attrs['class'] = 'cpf'
        self.fields['cep'].widget.attrs['class'] = 'cep'
        self.fields['celular'].widget.attrs['class'] = 'celular'
        self.fields['telefone'].widget.attrs['class'] = 'telefone'
        self.fields['falecido'].widget.attrs['class'] = 'falecido'
        self.fields['dt_promessa'].widget.attrs['class'] = 'dt_promessa'
        self.fields['dt_nascimento'].widget.attrs['class'] = 'dt_nascimento'
        self.fields['dt_matrimonio'].widget.attrs['class'] = 'dt_matrimonio'
        self.fields['atestado_obito'].widget.attrs['class'] = 'atestado_obito'

apps/members/views.py
import datetime
import logging

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.views.decorators.http import require_GET
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, Border, Side
from openpyxl.utils import get_column_letter
from xhtml2pdf import pisa

from .models import Membros
from ..pastorais.models import Pastorais


@login_required
@require_GET
def members(request):
    logging.info('Listando membros...')
    
    members_list = Membros.objects.all().prefetch_related('pastorais').select_related('profession').order_by("nome_completo")
    
    filter_params = request.GET.get("search", "")
    if filter_params:
        members_list = members_list.filter(
            Q(nome_completo__icontains=filter_params)
        )
    else:
        members_list = members_list.order_by("nome_completo")

    paginator = Paginator(members_list, 10)
    page = request.GET.get("page", 1)
    try:
        members_list = paginator.page(page)
    except PageNotAnInteger as e:
        logging.error('Numero de pagina não e int: %s', str(e))
        members_list = paginator.page(1)
    except EmptyPage as e:
        logging.error('Pagina Vazia: %s', str(e))
        members_list = paginator.page(paginator.num_pages)

    context = {
        "members_list": members_list,
        "paginator": paginator,
        "page": page,
    }
    logging.info("Lista de membros carregada com sucesso!")
    return render(request, "members/list_members.html", context)


@login_required
@require_GET
def member_details(request, pk):
    membro = get_object_or_404(Membros, pk=pk)

    context = {
        'membro': membro,
    }

    return render(request, "members/member_details.html", context)


@login_required
@require_GET
def export_pdf(request):
    members_list = Membros.objects.all().order_by("nome_completo")
    date = datetime.date.today()
    template_path = 'members/exports/export_pdf.html'
    context = {
        'members_list': members_list,
        'date': date
    }

    colunas_selecionadas = request.GET.getlist('colunas')
    if colunas_selecionadas:
        context['colunas_selecionadas'] = colunas_selecionadas
    else:
        context['colunas_selecionadas'] = ['Selecionar Tudo']

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="lista_de_membros_cadastrados.pdf"'

    template = get_template(template_path)
    table_data = create_table_data_pdf(context['members_list'], context.get('colunas_selecionadas'))
    context['table_data'] = table_data
    html = template.render(context)

    pisa_status = pisa.CreatePDF(html, dest=response)

    if pisa_status.err:
        return HttpResponse('Tivemos alguns erros <pre>' + html + '</pre>')

    return response


def create_table_data_pdf(members_list, colunas_selecionadas):
    opcoes_pastorais = Pastorais.pastoral_choices
    opcoes_elos = Membros.elo_choices
    headers = ['Selecionar Tudo', 'Nome', 'Data de Nascimento', 'Telefone', 'Celular', 'Orientador', 'Pastoral',
               'Elo']

    if 'Selecionar Tudo' in colunas_selecionadas:
        colunas_selecionadas.remove('Selecionar Tudo')

    if colunas_selecionadas:
        headers = [header for header in headers if header in colunas_selecionadas]

    data = []
    for member in members_list:
        member_data = []
        for header in headers:
            if header == 'Nome':
                member_data.append(member.nome_completo if member.nome_completo is not None else 'Não Informado')
            elif header == 'Data de Nascimento':
                member_data.append(
                    member.dt_nascimento.strftime('%d/%m/%Y') if member.dt_nascimento else 'Não Informado')
            elif header == 'Telefone':
                member_data.append(member.telefone if member.telefone is not None else 'Não Informado')
            elif header == 'Celular':
                member_data.append(member.celular if member.celular is not None else 'Não Informado')
            elif header == 'Orientador':
                member_data.append(member.mentor if member.mentor is not None else 'Não Informado')
            elif header == 'Pastoral':
                pastoral_nomes = [pastoral.nome for pastoral in member.pastorais.all() if pastoral.nome[0] is not None]
                pastoral_descriptions = [choice[1] for choice in opcoes_pastorais if choice[0] in pastoral_nomes]
                member_data.append(', '.join(pastoral_descriptions) if pastoral_descriptions else 'Não Informado')
            elif header == 'Elo':
                elo_description = next((choice[1] for choice in opcoes_elos if choice[0] == member.elo), 'Não Informado')
                member_data.append(elo_description)

        data.append(member_data)

    return data


@login_required
@require_GET
def export_excel(request):
    opcoes_pastorais = Pastorais.pastoral_choices
    opcoes_elos = Membros.elo_choices
    members_list = Membros.objects.all()
    colunas_selecionadas = request.GET.getlist('colunas')
    if not colunas_selecionadas or 'Selecionar Tudo' in colunas_selecionadas:
        colunas_selecionadas = ['Nome', 'Data de Nascimento', 'Telefone', 'Celular', 'Orientador', 'Pastoral',
                                'Elo']

    if 'Selecionar Tudo' in colunas_selecionadas:
        colunas_selecionadas.remove('Selecionar Tudo')

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=lista_de_membros_cadastrados.xlsx'

    workbook = Workbook()
    sheet = workbook.active

    headers = colunas_selecionadas
    sheet.append(headers)

    for member in members_list:
        member_data = []
        for header in colunas_selecionadas:
            if header == 'Nome':
                member_data.append(member.nome_completo if member.nome_completo is not None else 'Não Informado')
            elif header == 'Data de Nascimento':
                member_data.append(
                    member.dt_nascimento.strftime('%d/%m/%Y') if member.dt_nascimento else 'Não Informado')
            elif header == 'Telefone':
                member_data.append(member.telefone if member.telefone is not None else 'Não Informado')
            elif header == 'Celular':
                member_data.append(member.celular if member.celular is not None else 'Não Informado')
            elif header == 'Orientador':
                member_data.append(member.mentor if member.mentor is not None else 'Não Informado')
            elif header == 'Pastoral':
                pastoral_nomes = [pastoral.nome for pastoral in member.pastorais.all() if pastoral.nome[0] is not None]
                pastoral_descriptions = [choice[1] for choice in opcoes_pastorais if choice[0] in pastoral_nomes]
                member_data.append(', '.join(pastoral_descriptions) if pastoral_descriptions else 'Não Informado')
            elif header == 'Elo':
                elo_description = next((choice[1] for choice in opcoes_elos if choice[0] == member.elo), 'Não Informado')
                member_data.append(elo_description)
            else:
                member_data.append('')

        sheet.append(member_data)

        for col_num, col_header in enumerate(headers, 1):
            col_letter = get_column_letter(col_num)
            col_width = len(str(col_header)) + 10  
            for row in sheet.iter_rows(min_row=1, max_row=1):
                cell = row[col_num - 1]
                cell.value = col_header
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                cell.font = Font(bold=True)
                cell.border = Border(left=Side(border_style='thin'), right=Side(border_style='thin'))
                sheet.column_dimensions[col_letter].width = col_width

        for row in sheet.iter_rows(min_row=2):
            for cell in row:
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                cell.border = Border(left=Side(border_style='thin'), right=Side(border_style='thin'),
                                     top=Side(border_style='thin'), bottom=Side(border_style='thin'))

    workbook.save(response)
    return response

apps/templates/members/list_members.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} Página em Branco {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<div class="body flex-grow-1">
    <div class="mt-5">
        <a class="p-2 ms-3" href="{% url 'home' %}">
            <i class="fa fa-arrow-left"></i> Voltar para a página inicial</a>
        <a class="btn btn-sm btn-info dropdown-toggle" role="button" id="dropdownMenuLink"
           data-bs-toggle="dropdown" aria-expanded="false">
            Exportar
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exportModalPdf">
                <i class="fa fa-file-pdf-o pe-1"></i>PDF
            </a>
            </li>
            <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exportModalExcel">
                <i class="fa fa-file-excel-o pe-1"></i>EXCEL</a>
            </li>
        </ul>
    </div>

    <form action="" method="GET">
        <div class="col-sm-12">
            <div class="form-group mt-5 px-2 ms-3 me-3">
                <div class="input-group ">
                    <input class="form-control" id="search" name="search"
                           placeholder="Pesquise um membro por nome"
                           type="text"
                           data-placement="top" data-bs-toggle="tooltip"
                           title="Informe o nome do membro que deseja pesquisar">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">
                            <i class="fa fa-search"></i>
                            <span class="sr-only">Pesquisar</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="table-responsive text-center p-2 ms-3 me-3" id="data-box">
        <table class="table table-hover table-bordered table-full-width">
            <thead class="text-start table-light">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Data de Nascimento</th>
                <th scope="col">Telefone</th>
                <th scope="col">Celular</th>
                <th scope="col">Pastoral</th>
                <th scope="col">Elo</th>
            </tr>
            </thead>
            <tbody class="text-start">
            {% for member in members_list %}
            <tr>
                <td scope="row">
                    <a class="text-info" data-placement="top"
                       data-bs-toggle="tooltip" href="{% url 'member_details' member.id %}"
                       title="Veja mais detalhes sobre este membro" style="text-decoration:none">
                        {{ member.nome_completo }}
                    </a>
                </td>
                <td scope="row">
                    {{ member.dt_nascimento | date:"d/m/Y" }}
                </td>
                <td scope="row">{% if member.telefone %}{{ member.telefone }}{% else %} Não informado {% endif %}</td>
                <td scope="row">{% if member.celular %}{{ member.celular }}{% else %} Não informado {% endif %}</td>
                <td scope="row" data-bs-toggle="tooltip" data-bs-placement="top"
                    title="Para saber em quais pastorais que este membro pertence, acesse a tela de detalhes">
                    {% if member.pastorais %} {{member.pastorais.count}} pastorais {% else %} Não informado{% endif %}
                </td>
                <td scope="row">{% if member.elo %} {{member.get_elo_display}} {% else %} Não informado {% endif %}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="ml-2 mr-2 alert alert-warning" role="alert">
                    <strong>Nenhum dado encontrado.</strong>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% if members_list %}
    <div class="col-sm-12">
        {% include 'includes/pagination.html' with page=members_list %}
    </div>
    {% endif %}
    {% include 'includes/modal_export_pdf.html' %}
    {% include 'includes/modal_export_excel.html' %}
</div>

{% endblock content %}

apps/templates/members/member_details.html
{% extends 'layouts/base.html' %}
{% block titulo %}Mais Detalhes | {% endblock %}
{% load static %}
{% block content %}

<div class="col ">
    {% include 'includes/messages_component.html' with messages=messages %}
    <div class="mt-4">
        <a class="p-2 ms-3" href="{% url 'list-members' %}">
            <i class="fa fa-arrow-left"></i> Voltar</a>
    </div>
    <div class="card ms-4 me-4 mt-4 mb-4">
        <h5 class="card-header">
            Dados pessoais de {{ membro.nome_completo }}
        </h5>

        <div class="card-body">
            <table class="table">
                <tbody>
                <!-- Dados Pessoais -->
                <tr>
                    <td>Data de Nascimento</td>
                    <td>{{ membro.dt_nascimento |date:"d/m/Y" }}</td>
                </tr>
                <tr>
                    <td>CPF</td>
                    <td>{% if membro.cpf %}{{ membro.cpf }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Sexo</td>
                    <td>{% if membro.sexo %}{{ membro.sexo }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Telefone</td>
                    <td>{{ membro.telefone }}</td>
                </tr>
                <tr>
                    <td>Celular</td>
                    <td>{{ membro.celular }}</td>
                </tr>
                <tr>
                    <td>E-mail</td>
                    <td>{{ membro.email }}</td>
                </tr>

                <tr>
                    <td>Endereço</td>
                    <td>{% if membro.address %}{{ membro.address }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Bairro</td>
                    <td>{% if membro.neighborhood %}{{ membro.neighborhood }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Cidade</td>
                    <td>{% if membro.city %}{{ membro.city }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Estado</td>
                    <td>{% if membro.state %}{{ membro.state }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>CEP</td>
                    <td>{% if membro.cep %}{{ membro.cep }}{% else %}Não informado{% endif %}</td>
                </tr>
                <!-- Profissionais -->
                <tr>
                    <td>Profissão</td>
                    <td>{% if membro.profession %}{{ membro.profession }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Formação</td>
                    <td>
                        {% if membro.education %}
                        {{ membro.education }}
                        {% else %}
                        Não informado
                        {% endif %}
                    </td>
                </tr>
                {% if membro.estado_civil == 'Casado' %}
                <tr>
                    <td>Conjugue</td>
                    <td>{% if membro.conjugue %}{{ membro.conjugue }}{% else %}Não informado{% endif %}</td>
                </tr>
                {% if membro.conjugue and membro.dt_matrimonio %}
                <tr>
                    <td>Data do matrimônio</td>
                    <td>
                       {% if membro.dt_matrimonio %} {{ membro.dt_matrimonio | date:"d/m/Y" }}{% else %}Não informado{% endif %}
                    </td>
                </tr>
                {% else %}
                {% if membro.estado_civil %}{{ membro.estado_civil }}{% else %}Não informado{% endif %}
                {% endif %}
                {% endif %}
                <tr>
                    <td>Aposentado</td>
                    <td>{% if membro.is_retired %}SIM{% else %}Não{% endif %}</td>
                </tr>
                
                <tr>
                    <td>Mentor</td>
                    <td>{% if membro.mentor %}{{ membro.mentor }}{% else %}Não informado{% endif %}</td>
                </tr>
                <tr>
                    <td>Data da promessa</td>
                    <td>{% if membro.dt_promessa %}{{ membro.dt_promessa |date:"d/m/Y"}} {% else %}Não informado {%endif%}
                    </td>
                </tr>

                <tr>
                    <td>Formador(s)</td>
                    <td>
                        {% for formador in membro.formadores.all %}
                        {{ formador.nome }},
                        {% empty %}
                        Não informado
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td>Pastoral(s)</td>
                    <td>
                        {% for pastoral in membro.pastorais.all %}
                        {{ pastoral.get_nome_display }},
                        {% empty %}
                        Não informado
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td>Afastado</td>
                    <td>{% if membro.afastado %}Não{% else %}Sim{% endif %}</td>
                </tr>
                <tr>
                    <td>Falecido</td>
                    <td>{% if membro.atestado_obito %}
                        Sim
                        <a href="{{membro.atestado_obito.url }}">
                            Atestado de obito</a>
                        {% else %}
                        Não
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}